### ISSUE TITLE
插件推荐：Eclipse-Class-Decompiler

### ISSUE THREAD

**Issue by yansheng836** [waylau/everything-in-eclipse#1]
- 名称：class反编译器。
- 推荐原因：一般在不使用原生jdk的情况下，eclipse的内置反编译器是可以正常工作的，具体操作：选中类-->Ctrl+鼠标左键，可跳到该类的jdk源码编译的class文件中。但是如果使用依赖包时（如Spring框架、Mybatis框架等），可能会找不到对应的class文件，即使你手动选择路径，有时也会不行！安装该插件（`Eclipse-Class-Decompiler`）便可轻松解决该问题。
- 详细说明请看：github仓库：<https://github.com/cnfree/Eclipse-Class-Decompiler>

**Comment by waylau** [comment]
@yansheng836 已收录，感谢反馈
